export const girlsRiseUp = {
    name: 'Girls Rise Up',
    quizlet: '',
    lines: [
        [
            '那就等着沦陷吧如果爱情真伟大',
            'nà jiù děng zhe lún xiàn ba rú guǒ ài qíng zhēn wěi dà',
            'then wait for the fall, if love is really great',
        ],
        [
            '我有什么好毛病难道我比别人差',
            'wǒ yǒu shén me hǎo máo bìng nán dào wǒ bǐ bié rén chà',
            "what's wrong with me, am i worse than others?",
        ],
        [
            '谁要周末待在家对着电视爆米花',
            'shéi yào zhōu mò dài zài jiā duì zhe diàn shì bào mǐ huā',
            'who wants to stay home and popcorn on the tv on weekends?',
        ],
        [
            '看你说的情话哭得眼泪哗啦啦',
            'kàn nǐ shuō de qíng huà kū dé yǎn lèi huālā la',
            'i cried when i saw what you said',
        ],
        ['', '', ''],
        [
            '十个男人七个傻傻呆呆九个坏',
            'shí gè nán rén qī gè shǎ shǎ dāi dāi jiǔ gè huài',
            'ten men, seven stupid, nine bad',
        ],
        [
            '还有一个人爱姐妹们跳出来',
            'hái yǒu yī gè rén ài jiě mèi men tiào chū lái',
            'and one loves the sisters to jump out',
        ],
        ['可爱甜言蜜语把他骗过来', 'kě ài tián yán mì yǔ bǎ tā piàn guò lái', 'cute sweet words tricked him'],
        ['好好爱 不再让他离开', 'hǎo hǎo ài bù zài ràng tā lí kāi', "love well, don't let him go"],
        [
            '十个男人七个傻傻呆呆九个坏',
            'shí gè nán rén qī gè shǎ shǎ dāi dāi jiǔ gè huài',
            'ten men, seven stupid, nine bad',
        ],
        [
            '还有一个人爱姐妹们跳出来',
            'hái yǒu yī gè rén ài jiě mèi men tiào chū lái',
            'and one loves the sisters to jump out',
        ],
        ['可爱甜言蜜语把他骗过来', "kě ài tián yán mì yǔ bǎ tā piàn guò lái", 'cute sweet words tricked him'],
        ['好好爱 不再让他离开', 'hǎo hǎo ài bù zài ràng tā lí kāi', "love well, don't let him go"],
        ['', '', ''],
        [
            '找个人恋爱吧不让你来告诉你呀',
            'zhǎo gè rén liàn ài ba bù ràng nǐ lái gào sù nǐ ya',
            "find someone to fall in love with, i won't let you tell you",
        ],
        [
            '像枯萎的玫瑰花心里的雨拼命下',
            'xiàng kū wěi de méi guī huā xīn lǐ de yǔ pīn mìng xià',
            'like a withered rose, the rain in my heart is desperately falling',
        ],
        [
            '从今以后别怕我太阳那么大',
            'cóng jīn yǐ hòu bié pà wǒ tài yáng nàme dà',
            "don't be afraid of my sun from now on",
        ],
        [
            '如果相爱要长大一个人接受她',
            'rú guǒ xiāng ài yào zhǎng dà yī gè rén jiē shòu tā',
            'if you love each other, you will grow up and accept her alone',
        ],
        ['', '', ''],
        [
            '十个男人七个傻傻呆呆九个坏',
            'shí gè nán rén qī gè shǎ shǎ dāi dāi jiǔ gè huài',
            'ten men, seven stupid, nine bad',
        ],
        [
            '还有一个人爱姐妹们跳出来',
            'hái yǒu yī gè rén ài jiě mèi men tiào chū lái',
            'and one loves the sisters to jump out',
        ],
        ['可爱甜言蜜语把他骗过来', 'kě ài tián yán mì yǔ bǎ tā piàn guò lái', 'cute sweet words tricked him'],
        ['好好爱 不再让他离开', 'hǎo hǎo ài bù zài ràng tā lí kāi', "love well, don't let him go"],
        [
            '十个男人七个傻傻呆呆九个坏',
            'shí gè nán rén qī gè shǎ shǎ dāi dāi jiǔ gè huài',
            'ten men, seven stupid, nine bad',
        ],
        [
            '还有一个人爱姐妹们跳出来',
            'hái yǒu yī gè rén ài jiě mèi men tiào chū lái',
            'and one loves the sisters to jump out',
        ],
        ['可爱甜言蜜语把他骗过来', "kě ài tián yán mì yǔ bǎ tā piàn guò lái", 'cute sweet words tricked him'],
        ['好好爱 不再让他离开', 'hǎo hǎo ài bù zài ràng tā lí kāi', "love well, don't let him go"],
        ['', '', ''],
        [
            '十个男人七个傻傻呆呆九个坏',
            'shí gè nán rén qī gè shǎ shǎ dāi dāi jiǔ gè huài',
            'ten men, seven stupid, nine bad',
        ],
        [
            '还有一个人爱姐妹们跳出来',
            'hái yǒu yī gè rén ài jiě mèi men tiào chū lái',
            'and one loves the sisters to jump out',
        ],
        ['可爱甜言蜜语把他骗过来', 'kě ài tián yán mì yǔ bǎ tā piàn guò lái', 'cute sweet words tricked him'],
        ['好好爱 不再让他离开', 'hǎo hǎo ài bù zài ràng tā lí kāi', "love well, don't let him go"],
        [
            '十个男人七个傻傻呆呆九个坏',
            'shí gè nán rén qī gè shǎ shǎ dāi dāi jiǔ gè huài',
            'ten men, seven stupid, nine bad',
        ],
        [
            '还有一个人爱姐妹们跳出来',
            'hái yǒu yī gè rén ài jiě mèi men tiào chū lái',
            'and one loves the sisters to jump out',
        ],
        ['可爱甜言蜜语把他骗过来', "kě ài tián yán mì yǔ bǎ tā piàn guò lái", 'cute sweet words tricked him'],
        ['好好爱 不再让他离开', 'hǎo hǎo ài bù zài ràng tā lí kāi', "love well, don't let him go"],
        ['', '', ''],
        [
            '把他骗过来好好爱不再让他离开',
            'bǎ tā piàn guò lái hǎo hǎo ài bù zài ràng tā lí kāi',
            "lie him over and love him and don't let him go",
        ],
        [
            '把他骗过来好好爱不再让他离开',
            'bǎ tā piàn guò lái hǎo hǎo ài bù zài ràng tā lí kāi',
            "lie him over and love him and don't let him go",
        ],
        ['好好爱不再让他离', 'hǎo hǎo ài bù zài ràng tā lí kā', "love well, don't let him g"],
    ],
};
