export const twentiesThirties = {
    name: 'Twenties Thirties',
    quizlet: 'https://quizlet.com/683964766/twenties-thirties-ronghao-li-flash-cards/',
    lines: [
        ["邮递的工人", "yóu dì de gōng rén", "A postal worker"],
        ["儿科的医生", "ér kē de yī shēng", "A pediatric doctor"],
        ["几个开旅馆的人", "jǐ gè kāi lǚ guǎn de rén", "A few people that opened a motel"],
        ["园丁喝的茶", "yuán dīng hē de chá", "The gardener's tea"],
        ["理发师的话", "lǐ fā shī de huà", "The hairdresser's words"],
        ["修鞋匠的家没想过伟大", "xiū xié jiàng de jiā méi xiǎng guò wěi dà", "The shoe maker's house and more things I couldn't think of"],
        ['', '', ''],
        ["二三十岁的人", "èr sān shí suì de rén", "People in their 20s-30s"],
        ["傍晚黄昏还等对的人", "bàng wǎn huáng hūn hái děng duì de rén", "Even as the night fell, we have been waiting for the right person"],
        ["醉的好坏不分哭的大声", "zuì de hǎo huài bù fēn kū de dà shēng", "Getting drunk -whether this is good or bad- we were just crying loudly"],
        ["记录著青春", "jì lù zhe qīng chūn", "Making memories of our youth"],
        ["二三十岁的人", "èr sān shí suì de rén", "People in their 20s-30s"],
        ["奋不顾身微笑着成人", "fèn bù gù shēn wēi xiào zhe chéng rén", "We were thinking that we could do anything we wanted, smiling while growing up"],
        ["回头看了看路程", "huí tóu kàn le kàn lù chéng", "Turning back, we see our journey so far."],
        ['', '', ''],
        ["航海去了哪", "háng hǎi qù le nǎ", "Where have we navigated to?"],
        ["主编爱的他", "zhǔ biān ài de tā", "There was the person whom the editor loved"],
        ["还有个别作曲家", "hái yǒu gè bié zuò qū jiā", "And there are still a few composers"],
        ["我们都很好", "wǒ men dōu hěn hǎo", "We are all doing well"],
        ["没觉得无聊", "méi jué dé wú liáo", "We don't think it's boring"],
        ["天气那么好没想过会老", "tiān qì nà me hǎo méi xiǎng guò huì lǎo", "The weather is so nice, I never thought we'd get older"],
        ['', '', ''],
        ["二三十岁的人", "èr sān shí suì de rén", "People in their 20s-30s"],
        ["傍晚黄昏还等对的人", "bàng wǎn huáng hūn hái děng duì de rén", "Even as the night fell, we have been waiting for the right person"],
        ["醉的好坏不分哭的大声", "zuì de hǎo huài bù fēn kū de dà shēng", "Getting drunk -whether this is good or bad- we were just crying loudly"],
        ["记录著青春", "jì lù zhe qīng chūn", "Making memories of our youth"],
        ["二三十岁的人", "èr sān shí suì de rén", "People in their 20s-30s"],
        ["奋不顾身微笑着成人", "fèn bù gù shēn wēi xiào zhe chéng rén", "We were thinking that we could do anything we wanted, smiling while growing up"],
        ["回头看了看路程", "huí tóu kàn le kàn lù chéng", "Turning back, we see our journey so far."],
        ['', '', ''],
        ["有些快要想不起来的人吧", "yǒu xiē kuài yào xiǎng bù qǐ lái de rén ba", "Perhaps there are people we'll soon forget"],
        ["那些就是已经过去了的年华", "nà xiē jiù shì yǐ jīng guò qù le de nián huá", "They must have lived through their best years"],
        ['', '', ''],
        ["二三十岁的人", "èr sān shí suì de rén", "People in their 20s-30s"],
        ["傍晚黄昏还等对的人", "bàng wǎn huáng hūn hái děng duì de rén", "Even as the night fell, we have been waiting for the right person"],
        ["醉的好坏不分哭的大声", "zuì de hǎo huài bù fēn kū de dà shēng", "Getting drunk -whether this is good or bad- we were just crying loudly"],
        ["记录著青春", "jì lù zhe qīng chūn", "Making memories of our youth"],
        ["奋不顾身微笑着成人", "fèn bù gù shēn wēi xiào zhe chéng rén", "We were thinking that we could do anything we wanted, smiling while growing up"],
        ["回头看了看路程", "huí tóu kàn le kàn lù chéng", "Turning back, we see our journey so far."]
    ]
    ,
};
